baseURL = "/"
languageCode = "en-us"
title = "Updating Data"
theme = "learn"
metaDataFormat = "yaml"

[params]
  themeVariant = "green"

# For search functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]